# Generated by Django 4.0.6 on 2022-08-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Preservação de Madeiras', 'Preserv')], default='Preservação de Madeiras', max_length=50)),
            ],
        ),
    ]
